# Generated by Django 3.2.5 on 2021-07-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_subcategory', models.CharField(max_length=255, unique=True)),
                ('subcategory_slug', models.SlugField(max_length=255)),
                ('article_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategory',
            },
        ),
    ]
