# Generated by Django 3.2.5 on 2021-07-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='article_subcategory',
            new_name='subcategory_name',
        ),
    ]
